/// Flutter icons UniIcon2
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  UniIcon2
///      fonts:
///       - asset: fonts/UniIcon2.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class UniIcon2 {
  UniIcon2._();

  static const _kFontFam = 'UniIcon2';
  static const /*String?*/ _kFontPkg = null;

  static const IconData spin = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
