/// Flutter icons UniIcon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  UniIcon
///      fonts:
///       - asset: fonts/UniIcon.ttf
///
/// 
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class UniIcon {
  UniIcon._();

  static const _kFontFam = 'UniIcon';
  static const _kFontPkg = null;

  static const IconData unicoin = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_enabled = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData my_union = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData customer_service = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search_enabled = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search_disabled = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData new_union = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData feed_enabled = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData feed_disabled = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_disabled = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData my_color = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData account_box = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ticket_price = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar = IconData(0xf133, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData youtube = IconData(0xf167, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData instagram = IconData(0xf16d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData soundcloud = IconData(0xf1be, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData birthday_cake = IconData(0xf1fd, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
