/// Flutter icons UniIcon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  UniIcon
///      fonts:
///       - asset: fonts/UniIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class UniIcon {
  UniIcon._();

  static const _kFontFam = 'UniIcon';
  static const _kFontPkg = null;

  static const IconData home_enabled = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData my_union = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData customer_service = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search_enabled = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search_disabled = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData new_union = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData feed_enabled = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData feed_disabled = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_disabled = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData my_color = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ticket_price = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData more_info_1 = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mail = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData like_ena = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData like_dis = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fix = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData comment = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat_dis = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat_ena = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData more_info = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData unicoin = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData instagram = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData soundcloud = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData youtube = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
